# Generated by Django 5.1.6 on 2026-03-28 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_result_archive_folder'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='group',
            new_name='core_group_is_arch_2e54eb_idx',
            old_name='core_group_is_archi_1b7045_idx',
        ),
        migrations.RenameIndex(
            model_name='group',
            new_name='core_group_name_9ccf81_idx',
            old_name='core_group_name_221cf5_idx',
        ),
        migrations.RenameIndex(
            model_name='module',
            new_name='core_module_is_demo_24ada2_idx',
            old_name='core_module_is_demo_44bca6_idx',
        ),
        migrations.RenameIndex(
            model_name='module',
            new_name='core_module_name_e8e482_idx',
            old_name='core_module_name_2b4cbf_idx',
        ),
        migrations.RenameIndex(
            model_name='modulesubjectconfig',
            new_name='core_module_subject_d0a200_idx',
            old_name='core_module_subject_4d19b7_idx',
        ),
        migrations.RenameIndex(
            model_name='question',
            new_name='core_questi_subject_a4e3ea_idx',
            old_name='core_questi_subject_693b78_idx',
        ),
        migrations.RenameIndex(
            model_name='resultarchivefolder',
            new_name='core_result_name_7d4b17_idx',
            old_name='core_result_name_2df4d0_idx',
        ),
        migrations.RenameIndex(
            model_name='subject',
            new_name='core_subjec_is_demo_884a50_idx',
            old_name='core_subjec_is_demo_fa7fde_idx',
        ),
        migrations.RenameIndex(
            model_name='testattempt',
            new_name='core_testat_partici_976d08_idx',
            old_name='core_testat_partici_642abf_idx',
        ),
        migrations.RenameIndex(
            model_name='testattempt',
            new_name='core_testat_partici_44f744_idx',
            old_name='core_testat_partici_66ded2_idx',
        ),
        migrations.RenameIndex(
            model_name='testattempt',
            new_name='core_testat_expires_f29ad0_idx',
            old_name='core_testat_expires_7e6370_idx',
        ),
        migrations.RenameIndex(
            model_name='testresult',
            new_name='core_testre_partici_0f2256_idx',
            old_name='core_testr_partici_2aa9b4_idx',
        ),
        migrations.RenameIndex(
            model_name='testresult',
            new_name='core_testre_group_i_250b3c_idx',
            old_name='core_testr_group_i_e42761_idx',
        ),
        migrations.RenameIndex(
            model_name='testresult',
            new_name='core_testre_module__31f8e7_idx',
            old_name='core_testr_module__677029_idx',
        ),
        migrations.RenameIndex(
            model_name='testresult',
            new_name='core_testre_archive_176a5f_idx',
            old_name='core_testr_archive_551b26_idx',
        ),
    ]
