# Generated by Django 5.1.6 on 2026-03-28 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_role_1fa9a5_idx',
            old_name='accounts_us_role_3e7d07_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_group_i_2c1702_idx',
            old_name='accounts_us_group_i_0d9787_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_is_arch_859284_idx',
            old_name='accounts_us_is_arc_4aa7fd_idx',
        ),
    ]
